# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'HCMUSAvatar' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HCMUSAvatar

  target 'HCMUSAvatarTests' do
    inherit! :search_paths
    # Pods for testing
  end

	pod 'RNFS', :path => ‘../node_modules/react-native-fs'
	pod 'RSKImageCropper'
	pod 'QBImagePickerController'

end
